version : '3'
services : 
    app :
        image : flask
        container_name : wookang_flask
        build :
            context : flask
            dockerfile : dockerfile
        environment :
            GIT_BRANCH : "main"
            TZ : "asiz/Seoul"
        ports : 
            - "16007:16007"
        