FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip python3-dev build-essential

RUN apt-get install git -y
RUN apt-get install -y tzdata

WORKDIR /app

RUN git clone https://github.com/LVturtle/flask_test.git .

COPY ./app /app

EXPOSE 5000

RUN pip3 install -r server/requirements.txt

ENTRYPOINT ["./entrypoint.sh"]